### ISSUE TITLE
Gérer le retour du nom du mouvement dans le Main

### ISSUE THREAD

**Issue by gabcomby** [GabrielC-34/H22-GR10-ReconnaissanceMouvement#5]
# Problème
Le nom du mouvement est compliqué à faire revenir dans le Main parce qu'il n'est pas toujours initialisé. En effet, si le programme ne détecte pas de mains, alors le nom est Null.

# Solution
Vérifier si l'on peut éviter ce genre de problème avec des if/else qui return la valeur ou non

**Comment by GuilhemDM** [comment]
Fixed
